// ---------------------------------------------------------------------------
// In-memory suggested index store
//
// Tracks every CREATE INDEX statement string generated by the rule engine
// across all /api/explain calls since server startup.
//
// No database, no file persistence, no expiry — resets on server restart.
// This is intentional and acceptable: QueryLens V1 is a single-user local
// demo tool with no authentication (see docs/requirements.md). The allowlist
// is only needed to prevent the /api/apply-index endpoint from executing
// arbitrary DDL submitted directly by a client — not to provide durable
// session management across restarts.
// ---------------------------------------------------------------------------

const knownStatements = new Set<string>();

/**
 * Records every statement string from a set of suggested indexes produced
 * by the rule engine. Called by explain.controller.ts after analyzePlan().
 */
export function recordSuggestedIndexes(statements: string[]): void {
  for (const statement of statements) {
    knownStatements.add(statement);
  }
}

/**
 * Returns true if this exact statement string was previously generated by
 * the rule engine and recorded via recordSuggestedIndexes().
 * Comparison is a strict string equality check — no normalization.
 */
export function isKnownSuggestion(statement: string): boolean {
  return knownStatements.has(statement);
}
