import { Pool } from 'pg';
import config from './env';

/**
 * Read-only pool — used by /api/query/execute and /api/explain.
 * Connects as `querylens_readonly` (SELECT only).
 */
export const readonlyPool = new Pool({
  connectionString: config.databaseUrlReadonly,
});

/**
 * Index-manager pool — retained for potential future use.
 * Connects as `querylens_index_manager`.
 *
 * NOTE: This pool is NOT used by /api/apply-index despite the role's name.
 * PostgreSQL's CREATE INDEX privilege model requires table *ownership* to
 * create indexes on existing tables — there is no grantable privilege that
 * allows a non-owning role to do this. Granting CREATE on the schema only
 * allows creating new objects, not indexing pre-existing tables owned by
 * another role. See adminPool below for what /api/apply-index actually uses.
 */
export const indexManagerPool = new Pool({
  connectionString: config.databaseUrlIndexManager,
});

/**
 * Admin pool — used exclusively by /api/apply-index to execute CREATE INDEX.
 * Connects as the superuser (DATABASE_URL) because PostgreSQL requires table
 * ownership to create indexes on pre-existing tables.
 *
 * Security model: the real safety control for this endpoint is NOT the DB role
 * but the exact-match check in suggestedIndexStore.ts — only statements
 * previously generated by the server's own rule engine are ever executed here,
 * so no client-supplied DDL can reach this pool. The adminPool is used purely
 * because it is the only connection that has the necessary table-ownership
 * privilege to run CREATE INDEX successfully.
 */
export const adminPool = new Pool({
  connectionString: config.databaseUrl,
});
